name: Test github actions
on:
  push:
    branches:
      - test-github-action
  pull_request:
    branches:
      - test-github-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test running python script
        run: python AI/tests/test_github_actions.py
      - name: runnining unit tests
        run: python AI/tests/test_script.py